name: 01-github-action

on:
  push:
  pull_request:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello world"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success job now
        run: |
          echo "failing now"
          exit 0
