name: 01-github-action
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "hello world"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: failed step
        run: |
          echo "failing now"
            exit 0
