name: 02-github-action

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  trigger-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "I was triggered by a(n) ${{ github.event_name }}"
